const houses = [
    {
      id: '1',
      Owner: 'Raul',
      name: 'House 1',
      address: 'East Side Cedar Cottage Toronto',
      rooms_number: 4,
      persons_number: 8,
      image: require('../assets/house1.jpg'),
      review: 10,
      price: 500,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    },
    {
      id: '2',
      Owner: 'Raul2',
      name: 'House 2',
      address: 'East Side Cedar Cottage Toronto',
      rooms_number: 4,
      persons_number: 8,
      image: require('../assets/house1.jpg'),
      review: 10,
      price: 5000,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    },
    {
        id: '3',
        Owner: 'Raul3',
        name: 'House 3',
        address: 'East Side Cedar Cottage Toronto',
        rooms_number: 4,
        persons_number: 8,
        image: require('../assets/house1.jpg'),
        review: 10,
        price: 40,
        interiors: [
          require('../assets/interior1.jpg'),
          require('../assets/interior2.jpg'),
          require('../assets/interior3.jpg'),
        ],
    },
    {
      id: '4',
      Owner: 'Raul4',
      name: 'House 4',
      address: 'East Side Cedar Cottage Toronto',
      rooms_number: 4,
      persons_number: 8,
      image: require('../assets/house1.jpg'),
      review: 10,
      price: 24,
      interiors: [
        require('../assets/interior1.jpg'),
        require('../assets/interior2.jpg'),
        require('../assets/interior3.jpg'),
      ],
    },
  ];
  
  export default houses;